# Generated by Django 4.1.2 on 2022-10-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Darbas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.CharField(max_length=100, verbose_name='Pavadinimas')),
                ('pastabos', models.TextField(max_length=300, verbose_name='Pastabos')),
            ],
        ),
        migrations.CreateModel(
            name='Darbuotojas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vardas', models.CharField(max_length=100, verbose_name='Vardas')),
                ('pavarde', models.CharField(max_length=100, verbose_name='Pavardė')),
                ('pareigos', models.CharField(max_length=100, verbose_name='Pareigos')),
            ],
        ),
        migrations.CreateModel(
            name='Klientas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vardas', models.CharField(max_length=100, verbose_name='Vardas')),
                ('pavarde', models.CharField(max_length=100, verbose_name='Pavardė')),
                ('imone', models.CharField(max_length=100, verbose_name='Įmonė')),
                ('kontaktai', models.TextField(max_length=150, verbose_name='Kontaktai')),
            ],
        ),
        migrations.CreateModel(
            name='Projektas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.CharField(max_length=100, verbose_name='Pavadinimas')),
                ('pradzia', models.DateField(blank=True, verbose_name='Pradžios data')),
                ('pabaiga', models.DateField(blank=True, verbose_name='Pabaigos data')),
                ('klientas', models.CharField(max_length=100, verbose_name='Klientas')),
                ('vadovas', models.CharField(max_length=100, verbose_name='Atsakingasis/vadovas')),
                ('darbuotojai', models.CharField(max_length=100, verbose_name='Darbuotojai')),
                ('darbai', models.CharField(max_length=100, verbose_name='Darbai')),
                ('saskaitos', models.FloatField(verbose_name='Sąskaitos')),
            ],
        ),
        migrations.CreateModel(
            name='Saskaita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('israsymo_data', models.DateField(blank=True, verbose_name='Išrašymo data')),
                ('suma', models.FloatField(verbose_name='Suma')),
            ],
        ),
    ]
