# Generated by Django 4.1.2 on 2022-10-19 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='darbas',
            options={'verbose_name': 'Darbas', 'verbose_name_plural': 'Darbai'},
        ),
        migrations.AlterModelOptions(
            name='darbuotojas',
            options={'verbose_name': 'Darbuotojas', 'verbose_name_plural': 'Darbuotojai'},
        ),
        migrations.AlterModelOptions(
            name='klientas',
            options={'verbose_name': 'Klientas', 'verbose_name_plural': 'Klientai'},
        ),
        migrations.AlterModelOptions(
            name='projektas',
            options={'verbose_name': 'Projektas', 'verbose_name_plural': 'Projektai'},
        ),
        migrations.AlterModelOptions(
            name='saskaita',
            options={'verbose_name': 'Saskaita', 'verbose_name_plural': 'Saskaitos'},
        ),
        migrations.AlterField(
            model_name='projektas',
            name='darbai',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.darbas'),
        ),
        migrations.AlterField(
            model_name='projektas',
            name='darbuotojai',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.darbuotojas'),
        ),
        migrations.AlterField(
            model_name='projektas',
            name='klientas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.klientas'),
        ),
        migrations.AlterField(
            model_name='projektas',
            name='saskaitos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.saskaita'),
        ),
    ]
