# Generated by Django 4.1.2 on 2022-10-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_alter_darbas_options_alter_darbuotojas_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projektas',
            name='cover',
            field=models.ImageField(null=True, upload_to='covers', verbose_name='Viršelis'),
        ),
    ]
