# Generated by Django 4.1.2 on 2022-10-25 08:59

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_projektas_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='projektas',
            name='description',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
