# Generated by Django 4.1.2 on 2022-10-25 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_projektas_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='klientas',
            name='logo',
            field=models.ImageField(null=True, upload_to='logos', verbose_name='Viršelis'),
        ),
    ]
